### PR TITLE
Add multiple sizes of each benchmark and analyze performance scaling

### PR DESCRIPTION
**Pull request by siddharth-krishna**
This PR makes the following changes:
- `generate-sizes.sh`: Generates multiple sizes of the pypsa-eur benchmarks by varying the spatial and temporal resolutions. This script replaces `solver_benchmark_pypsa_eur.py` and `generate.sh`, I'll update the README shortly
- Modifies the format of `metadata.yaml` to have a list of sizes of each benchmark, and move the size-dependent fields like "number of variables" into each size of the benchmark.
- After generating 36 sizes of the pypsa-eur benchmarks, the `filter-benchmarks.{sh,py}` scripts run Highs on them to filter out the ones that can be solved in under 1h
- The generated LP files are now being saved to GCP buckets instead of GDrive as this can be automated using `gsutil -m cp runner/benchmarks/*.lp <GCP-bucket-path>`
- The `benchmark_config.yaml` format has also been updated to have a list of sizes for each benchmark
- The runner has been modified to read the new format of `benchmark_config.yaml`, download LP files from the GCP bucket, and also save the size information of each benchmark to the result CSV files
- And thanks to Jacek:
  - The website has been updated to work with the new size data in the result CSV files
  - A new performance scaling page has been added to the website to compare performance vs benchmark size

To do on the generation/runners side:
- [x] Adapt the generation script to work on all benchmarks
- [x] Automatically query generated LPs for num vars etc and put into metadata file ~(also get num int/continuous vars) -- Daniele is adding this in the next PR!~
- [x] Adapt runner to work on sizes and write size info to results CSV

To do on the website side:
- [x] Adapt `home.py`, `compare.py`, and `history.py` to work with the new CSV format, but displaying all the data for all the sizes
- [x] `benchmarks.py` should extract the information under `Sizes:` in `metadata.csv` and display it in a separate table, showing the sizes available for each benchmark
- [x] Add a new page `scaling.py` that plots {runtime, memory consumption} vs {spatial resolution, num variables, num constraints} as in [this](https://discord.com/channels/1097854148965306470/1308340506824278047/1308340517024694323) picture, but with one line plot per benchmark. Also implement Daniele's suggested improvements to the pic. Here is the code I used as a reference:

```python
figures = [
    px.scatter(data, x='Spatial Resolution', y='Runtime (s)', color='Solver'),
    px.scatter(data, x='Num Variables', y='Runtime (s)', color='Solver'),
    px.scatter(data, x='Num Constraints', y='Runtime (s)', color='Solver'),
]

fig = make_subplots(rows=1, cols=len(figures)) 
fig.update_layout(height=400, width=1200, title_text='pypsa-eur-sec-*-24h: Runtime (s) vs Num Clusters / Num Variables / Num Constraints')

for i, figure in enumerate(figures):
    for trace in range(len(figure["data"])):
        fig.add_trace(figure["data"][trace], row=1, col=i+1)
        
fig.show()
```

### CODE REVIEW

**Comment by jacek-oet** [comment]
- benchmarks.py should extract the information under Sizes: in metadata.csv and display it in a separate table, showing the sizes available for each benchmark

image

- Adapt home.py, compare.py, and history.py to work with the new CSV format, but displaying all the data for all the sizes

image
image
image

**Comment by siddharth-krishna** [comment]
Thanks, Jacek. A couple of quick requests:

- [ ] `benchmarks.py`: Remove the row `Sizes` from the first table (Metadata). And add the size to the tooltip of each data point in the plot.
- [ ] `home.py` and `compare.py`: I don't think it's showing all the different sizes of data points? Could you check again on the latest commit on this branch? I hope I didn't mess up anything in my merge commit..
- [ ] `scaling.py`: instead of having one plot per benchmark name, let's try showing all benchmarks on the same plots? Could you implement this in its own commit so that we can revert it if the plot is too crowded. 🙏

**Comment by jacek-oet** [comment]
> Thanks, Jacek. A couple of quick requests:
> 
> * [x]  `benchmarks.py`: Remove the row `Sizes` from the first table (Metadata). And add the size to the tooltip of each data point in the plot.
> * [x]  `home.py` and `compare.py`: I don't think it's showing all the different sizes of data points? Could you check again on the latest commit on this branch? I hope I didn't mess up anything in my merge commit..
> * [x]  `scaling.py`: instead of having one plot per benchmark name, let's try showing all benchmarks on the same plots? Could you implement this in its own commit so that we can revert it if the plot is too crowded. 🙏

@siddharth-krishna I created PR for 3rd point https://github.com/open-energy-transition/solver-benchmark/pull/66

**Comment by siddharth-krishna** [comment]
Thanks, Jacek, that's great. I notice a small bug, could you please fix it?

`benchmarks.py` and `compare.py`
The tooltip shows the same size:
image
image

**Review by jacek-oet — APPROVED** [review]
LGTM

**Comment by siddharth-krishna** [comment]
@jacek-oet @danielelerede-oet I'm merging this PR in now, because I need it to do a test run of the new Jump-Highs benchmarks in #64 

I'm sorry, it's become a bit of a monster PR! There were a lot of parts that had to be changed to support multiple sizes of benchmarks. I've updated the original PR description with a list of changes. I can also walk you through anything confusing. Please let me know here if anything looks off or you have suggestions for improvement and I'll implement them in my next PR. 🙏

**Review by jacek-oet — COMMENTED** [review]
LGTM :)

**Pull request merged**
